### PR TITLE
Fixed header size for (6) Re-use your config

### PR DESCRIPTION
**Pull request by nc-ruth**

### CODE REVIEW

**Comment by repeatedly** [comment]
Ah, good catch!
Could you add your sign with `-s` for DCO?

**Comment by nc-ruth** [comment]
Hi @repeatedly 

What do you exactly mean? :) 
Can you help me out? 

Best regards,
Ruba

**Comment by ganmacs** [comment]
Please check and follow https://github.com/fluent/fluentd-docs-gitbook/pull/36/checks?check_run_id=136704733

**Comment by nc-ruth** [comment]
Thank you @ganmacs & @repeatedly :)

**Comment by repeatedly** [comment]
Thanks for the patch!

**Pull request merged**
