### PR TITLE
Add a bit more information about the time parameter / field

### PR DESCRIPTION
**Pull request by dobesv**
Note the appropriate format of the time field and add a warning about invalid time values.

### CODE REVIEW

**Comment by mlasevich** [comment]
That may be effectively correct, but misleading. Unless I am mistaken, query parameter and json field, while accomplishing similar thing of setting event time, are two distinct things handled by two different plugins. Query parameter is processed by the input plugin (`in_http`), while time field is processed by a parser parameter (`parser_json`)

**Comment by repeatedly** [comment]
@dobesv Could you follow DCO? https://github.com/apps/dco

> while time field is processed by a parser parameter (parser_json)

With default mode, time field processing is handled in `in_http`. This is tricky for both single record and multiple records....

**Comment by mlasevich** [comment]
> With default mode, time field processing is handled in `in_http`. This is tricky for both single record and multiple records....

Interesting, so there are 4 different/competing ways to provide time (and time syntax) in this case?
* query parameter in (`in_http`)
* field provided to the input (`in_http`)
* field provided to the parser (in any parser)
* `<extract>` clause in input (in any input)

is that correct?

**Comment by dobesv** [comment]
> Could you follow DCO? https://github.com/apps/dco

I don't really understand what that is or how to apply it.  I think these docs are now obsolete anyway and have to be re-written, so this PR can be closed but used as "inspiration" for a better PR.

**Pull request closed without merging**
