### PR TITLE
Split deprecated v3 installation

### PR DESCRIPTION
**Pull request by kenhys**
As already announced EOL in Dec 2021,  let's remove it.

https://www.fluentd.org/blog/schedule-for-td-agent-3-eol

### CODE REVIEW

**Comment by ashie** [comment]
How about move it to a separated page instead of removing it completely.
Some users might still want to refer it (since some our customers still use it).

**Comment by kenhys** [comment]
Thanks, I'll fix it.

**Comment by kenhys** [comment]
Instead of removing them, keep it separated section like this:

image

and navigation to v3.

image

also added guide for migration from v3.

image

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
