### PR TITLE
Update windows install steps for 4.0.0

### PR DESCRIPTION
**Pull request by kenhys**
It omits manual registration step as Windows service.

### CODE REVIEW

**Comment by repeatedly** [comment]
td-agent 3 is widely used. Could you separate section for td-agent 3 and td-agent 4?

**Comment by kenhys** [comment]
Thanks, I'll fix it.

**Comment by kenhys** [comment]
I've fixed to split into two sections.

image

**Comment by cosmo0920** [comment]
td-agent 4 is workable with MSYS2 build system to build C extension included gems such as winevt_c and certstore_c.
Adding MSYS2 description is future task?

**Comment by ashie** [comment]
> td-agent 4 is workable with MSYS2 build system to build C extension included gems such as winevt_c and certstore_c.
> Adding MSYS2 description is future task?

FYI: td-agent 4.0.0 has a bug for it: https://github.com/fluent-plugins-nursery/td-agent-builder/issues/129

**Comment by cosmo0920** [comment]
Oops. Adding MSYS2 description should be future task.... It should be added after 4.0.1 is released.

**Comment by repeatedly** [comment]
Thx!

**Pull request merged**
