### PR TITLE
plugin-development: api-plugin-filter.md: fix spelling mistake "steam…

### PR DESCRIPTION
**Pull request by maluueu**
…" => "stream"

### CODE REVIEW

**Review by cosmo0920 — APPROVED** [review]

**Review by cosmo0920 — CHANGES_REQUESTED** [review]
Could you follow DCO procedure?

**Comment by maluueu** [comment]
> Could you follow DCO procedure?

sure, give me a couple of minutes

**Comment by maluueu** [comment]
@cosmo0920 done 👍🏻

**Review by daipom — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
