### PR TITLE
Use curl -fsSL -o- consistently

### PR DESCRIPTION
**Pull request by brsolomon-deloitte**
Add some flags to curl to raise error on failed request and ensure
output is stdout. Use bash rather than text blocks.

### CODE REVIEW

**Comment by kenhys** [comment]
It seems to use `-fsSL` is better, but is `-o-` really needed? (I'm not sure)

**Comment by brsolomon-deloitte** [comment]
Yes, I suppose it is redundant in this case. From `man curl`

> Specifying the output as '-' (a single dash) will  force the output to be done to stdout.

But that would really only be useful if multiple `-o` are passed, now that I think about it.

**Comment by brsolomon-deloitte** [comment]
> It seems to use `-fsSL` is better, but is `-o-` really needed? (I'm not sure)

Removed in b2c2f06.

**Comment by kenhys** [comment]
@brsolomon-deloitte 

Thanks!

**Pull request merged**
